### ISSUE TITLE
how to get rawByte from qr code?

### ISSUE THREAD

**Issue by lintangtimur** [dlenski/python-zxing#20]
how to get rawByte from qr code? like from zxing decoder java

**Comment by dlenski** [comment]
See https://github.com/dlenski/python-zxing/issues/17#issuecomment-905728212; it's not currently possible given the limitations of the ZXing command-line runner.

**Comment by dlenski** [comment]
As of https://github.com/dlenski/python-zxing/commit/646766b508719c60c4b46d11a010826e2728aeca, this should Just Work™; use `zxing.BarCode.raw_bits`;

1. ZXing CLR can be told to output the raw bits as of 3.5.0
1. `python-zxing` knows how to request that as of #26 
   - … but disables it because it causes ZXing to crash, see https://github.com/zxing/zxing/issues/1682
1. ZXing CLR includes my fix https://github.com/zxing/zxing/issues/1683 as of 3.5.3
